{{- if .Values.configMaps }}
{{- range $name, $files := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" $ }}-{{ $name }}
data:
  {{- range $fileName, $content := $files }}
  {{ $fileName }}: |
    {{ $content | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}