version = 1
SPDX-PackageName = "bdp-commons"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/bdp-commons"

[[annotations]]
path = ["**go.sum", "**go.mod", ".gitignore", "LICENSE", ".editorconfig", ".env.example", ".pre-commit-config.yaml", "helm/**", ".github/**", "skeleton/**", "docker/**", "data-collectors/**/documentation/**", "data-collectors/**/infrastructure/**", "**.http", "data-collectors/**/LICENSE", "data-collectors/**/license-header.txt", "data-collectors/**/**.properties", "data-collectors/**/**.csv", "data-collectors/**/**.json", "data-collectors/**/**.txt", "data-collectors/**/**.pdf", "data-collectors/**/**.dat", "data-collectors/**/**.g4", "data-collectors/**/**.wsdl", "data-collectors/**/.env.example", "data-collectors/**/.gitignore", "webservices/**/**.properties", "webservices/bdp-api/Jenkinsfile-Production", "webservices/bdp-api/Jenkinsfile-Test", "webservices/bdp-api/Jenkinsfile-V2-Test", "data-collectors/environment-appa-bz-tenminutes/src/main/resources/META-INF/.ssh/known_hosts", "data-collectors/environment-appa-bz-tenminutes/utils/antlr4", "data-collectors/environment-appa-bz-tenminutes/utils/antlr4-grun", "data-collectors/environment-appa-bz-tenminutes/utils/antlr4-javac"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "data-collectors/**/**.jsp"
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
